import yt_dlp
import re
import os
import json
import tempfile
import base64
from .cache import smart_cache

def _get_cookie_file():
    """Resolves and returns the path to a valid cookie file, or None."""
    # 1. Check for Base64 encoded cookies (Production/Cloud environments)
    b64_cookies = os.getenv('YOUTUBE_COOKIES_BASE64')
    if b64_cookies:
        try:
            cookie_text = base64.b64decode(b64_cookies).decode('utf-8')
            # Write it to a secure temporary file
            fd, temp_path = tempfile.mkstemp(suffix='.txt')
            with os.fdopen(fd, 'w', encoding='utf-8') as f:
                f.write(cookie_text)
            print("[YouTube] Using Base64 Environment Cookies")
            return temp_path
        except Exception as e:
            print(f"[YouTube] Failed to decode Base64 cookies: {e}")

    # 2. Check for local configuration files (Development)
    config_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'config')
    txt_path = os.path.join(config_dir, 'youtube.com_cookies.txt')
    json_path = os.path.join(config_dir, 'youtube.com_cookies.json')
    
    if os.path.exists(txt_path):
        print("[YouTube] Using local txt Cookies")
        return txt_path
    
    # Optional: Convert JSON to Netscape if needed, but yt-dlp usually prefers Netscape txt natively.
    # For now, if we only find JSON, we convert it on the fly.
    if os.path.exists(json_path):
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                cookies_json = json.load(f)
            
            netscape_content = "# Netscape HTTP Cookie File\n# This file is generated by yt-dlp\n\n"
            for cookie in cookies_json:
                domain = cookie.get('domain', '')
                flag = 'TRUE' if cookie.get('hostOnly', False) == False else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                expiration = str(int(cookie.get('expirationDate', 0)))
                name = cookie.get('name', '')
                value = cookie.get('value', '')
                netscape_content += f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
                
            fd, temp_path = tempfile.mkstemp(suffix='.txt')
            with os.fdopen(fd, 'w', encoding='utf-8') as f:
                f.write(netscape_content)
            print("[YouTube] Using local JSON Cookies (converted to Netscape)")
            return temp_path
        except Exception as e:
            print(f"[YouTube] Failed to convert JSON cookies: {e}")

    return None

def _get_ydl_opts():
    """Build yt-dlp options with optional cookie support from env var"""
    opts = {
        'quiet': True,
        'no_warnings': True,
        'nocheckcertificate': True,
        'ignoreerrors': True,
        'no_color': True,
        'logtostderr': False,
    }
    
    cookie_file = _get_cookie_file()
    if cookie_file:
        opts['cookiefile'] = cookie_file
        
    return opts

YDL_OPTS_BASE = _get_ydl_opts()

def smart_autocorrect(query):
    """Uses YouTube search to find the correct title (best effort)."""
    try:
        print(f"   [YouTube] Autocorrecting '{query}'...")
        opts = {**YDL_OPTS_BASE, 'extract_flat': True}
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch1:{query}", download=False)
            if 'entries' in info and info['entries']:
                title = info['entries'][0]['title']
                clean = re.sub(r'\(.*?Lyrics.*?\)|\[.*?Video.*?\]|\(Official.*?\)', '', title, flags=re.IGNORECASE).strip()
                print(f"   [YouTube] Fixed -> '{clean}'")
                return clean
    except: pass
    return query

def search_youtube(query):
    """Returns a list of YouTube videos (Fallback)"""
    print(f"   [YouTube] Searching for: '{query}'")
    try:
        opts = {**YDL_OPTS_BASE, 'extract_flat': True}
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch5:{query}", download=False)
            
        if not info or 'entries' not in info: 
            return []
        
        songs = []
        for vid in info['entries']:
            if vid:
                songs.append({
                    "title": vid.get('title'),
                    "artist": vid.get('uploader'),
                    "image": f"https://img.youtube.com/vi/{vid.get('id')}/hqdefault.jpg",
                    "url": vid.get('url') or f"https://www.youtube.com/watch?v={vid.get('id')}",
                    "source": "yt",
                    "quality": "160kbps"
                })
        return songs
    except Exception as e:
        print(f"   [YouTube] Search failed: {e}")
        return []

def resolve_yt_stream(watch_url):
    """Resolves a Watch URL to a temporary audio stream URL using yt-dlp"""
    format_fallbacks = ['bestaudio/best', 'audio/best', 'best']
    
    for fmt in format_fallbacks:
        try:
            opts = {**YDL_OPTS_BASE, 'format': fmt, 'noplaylist': True}
            with yt_dlp.YoutubeDL(opts) as ydl:
                info = ydl.extract_info(watch_url, download=False)
                if info:
                    url = info.get('url')
                    if url:
                        return url
        except Exception as e:
            print(f"   [YouTube] Format '{fmt}' failed: {e}")
            continue
    
    print(f"   [YouTube] Stream resolution failed for: {watch_url}")
    return None

@smart_cache(ttl=600, validator=lambda x: x is not None)
def get_audio_link(search_term):
    """SINGLE-CALL Optimized search + resolve."""
    print(f"   [YouTube] Speed-matching: '{search_term}'")
    
    format_fallbacks = ['bestaudio/best', 'audio/best', 'best']
    
    for fmt in format_fallbacks:
        try:
            opts = {**YDL_OPTS_BASE, 'format': fmt, 'noplaylist': True}
            with yt_dlp.YoutubeDL(opts) as ydl:
                info = ydl.extract_info(f"ytsearch1:{search_term}", download=False)
                
            if info and 'entries' in info and info['entries']:
                url = info['entries'][0].get('url')
                if url:
                    return url
        except Exception as e:
            print(f"   [YouTube] Format '{fmt}' failed: {e}")
            continue
            
    return None

@smart_cache(ttl=7200, validator=lambda x: x is not None)
def get_video_url(search_term):
    """Finds a video stream URL (MP4) for background playback."""
    print(f"   [YouTube] Fetching Video: '{search_term}'")
    try:
        opts = {
            **YDL_OPTS_BASE,
            'format': 'bestvideo[ext=mp4]/bestvideo[ext=webm]/best[ext=mp4]/best',
            'noplaylist': True,
        }
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch1:{search_term}", download=False)
            
        if info and 'entries' in info and info['entries']:
            return info['entries'][0].get('url')
    except Exception as e:
        print(f"   [YouTube] Video URL extraction failed: {e}")
        
    return None
