import yt_dlp
import re
import os
import json
import tempfile
from .cache import smart_cache

def _get_ydl_opts():
    """Build yt-dlp options with optional cookie support from env var"""
    opts = {
        'quiet': True,
        'no_warnings': True,
        'nocheckcertificate': True,
        'ignoreerrors': True,
        'no_color': True,
        'logtostderr': False,
    }
    
    cookies_content = os.getenv('YOUTUBE_COOKIES')
    
    # Check for local files first if env var is not set
    if not cookies_content:
        config_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'config')
        json_path = os.path.join(config_dir, 'youtube.com_cookies.json')
        txt_path = os.path.join(config_dir, 'youtube.com_cookies.txt')
        
        if os.path.exists(json_path):
            with open(json_path, 'r', encoding='utf-8') as f:
                cookies_content = f.read()
        elif os.path.exists(txt_path):
            with open(txt_path, 'r', encoding='utf-8') as f:
                cookies_content = f.read()

    if cookies_content:
        try:
            cookies_json = json.loads(cookies_content)
            netscape_content = "# Netscape HTTP Cookie File\n# This file is generated by yt-dlp\n\n"
            for cookie in cookies_json:
                domain = cookie.get('domain', '')
                flag = 'TRUE' if cookie.get('hostOnly', False) == False else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                expiration = str(int(cookie.get('expirationDate', 0)))
                name = cookie.get('name', '')
                value = cookie.get('value', '')
                netscape_content += f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
                f.write(netscape_content)
                opts['cookiefile'] = f.name
                print(f"   [YouTube] Using cookies (JSON format)")
        except json.JSONDecodeError:
            with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
                f.write(cookies_content)
                opts['cookiefile'] = f.name
                print(f"   [YouTube] Using cookies (Netscape format)")
    
    return opts

YDL_OPTS_BASE = _get_ydl_opts()

def smart_autocorrect(query):
    """Uses YouTube search to find the correct title (best effort)."""
    try:
        print(f"   [YouTube] Autocorrecting '{query}'...")
        opts = {**YDL_OPTS_BASE, 'extract_flat': True}
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch1:{query}", download=False)
            if 'entries' in info and info['entries']:
                title = info['entries'][0]['title']
                clean = re.sub(r'\(.*?Lyrics.*?\)|\[.*?Video.*?\]|\(Official.*?\)', '', title, flags=re.IGNORECASE).strip()
                print(f"   [YouTube] Fixed -> '{clean}'")
                return clean
    except: pass
    return query

def search_youtube(query):
    """Returns a list of YouTube videos (Fallback)"""
    print(f"   [YouTube] Searching for: '{query}'")
    try:
        opts = {**YDL_OPTS_BASE, 'extract_flat': True}
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch5:{query}", download=False)
            
        if not info or 'entries' not in info: 
            return []
        
        songs = []
        for vid in info['entries']:
            if vid:
                songs.append({
                    "title": vid.get('title'),
                    "artist": vid.get('uploader'),
                    "image": f"https://img.youtube.com/vi/{vid.get('id')}/hqdefault.jpg",
                    "url": vid.get('url') or f"https://www.youtube.com/watch?v={vid.get('id')}",
                    "source": "yt",
                    "quality": "160kbps"
                })
        return songs
    except Exception as e:
        print(f"   [YouTube] Search failed: {e}")
        return []

def resolve_yt_stream(watch_url):
    """Resolves a Watch URL to a temporary audio stream URL using yt-dlp"""
    format_fallbacks = ['bestaudio/best', 'audio/best', 'best']
    
    for fmt in format_fallbacks:
        try:
            opts = {**YDL_OPTS_BASE, 'format': fmt, 'noplaylist': True}
            with yt_dlp.YoutubeDL(opts) as ydl:
                info = ydl.extract_info(watch_url, download=False)
                if info:
                    url = info.get('url')
                    if url:
                        return url
        except Exception as e:
            print(f"   [YouTube] Format '{fmt}' failed: {e}")
            continue
    
    print(f"   [YouTube] Stream resolution failed for: {watch_url}")
    return None

@smart_cache(ttl=600, validator=lambda x: x is not None)
def get_audio_link(search_term):
    """SINGLE-CALL Optimized search + resolve."""
    print(f"   [YouTube] Speed-matching: '{search_term}'")
    
    format_fallbacks = ['bestaudio/best', 'audio/best', 'best']
    
    for fmt in format_fallbacks:
        try:
            opts = {**YDL_OPTS_BASE, 'format': fmt, 'noplaylist': True}
            with yt_dlp.YoutubeDL(opts) as ydl:
                info = ydl.extract_info(f"ytsearch1:{search_term}", download=False)
                
            if info and 'entries' in info and info['entries']:
                url = info['entries'][0].get('url')
                if url:
                    return url
        except Exception as e:
            print(f"   [YouTube] Format '{fmt}' failed: {e}")
            continue
            
    return None

@smart_cache(ttl=7200, validator=lambda x: x is not None)
def get_video_url(search_term):
    """Finds a video stream URL (MP4) for background playback."""
    print(f"   [YouTube] Fetching Video: '{search_term}'")
    try:
        opts = {
            **YDL_OPTS_BASE,
            'format': 'bestvideo[ext=mp4]/bestvideo[ext=webm]/best[ext=mp4]/best',
            'noplaylist': True,
        }
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(f"ytsearch1:{search_term}", download=False)
            
        if info and 'entries' in info and info['entries']:
            return info['entries'][0].get('url')
    except Exception as e:
        print(f"   [YouTube] Video URL extraction failed: {e}")
        
    return None
